name: Deployment Pipeline

on:
    push:
        branches:
            - main
    pull_request:
        branches: [main]
        types: [opened, synchronize]
    
jobs:
    simple_deployment_pipeline:
        runs-on: ubuntu-20.04
        steps:
            - name: Checkout directory
              uses: actions/checkout@v4
            
            - name: Set up Nodejs
              uses: actions/setup-node@v4

            - name: Install dependencies
              run: npm install
              working-directory: ./bloglist-backend

            - name: test
              run: npm run test
              working-directory: ./bloglist-backend

            - name: Trigger Deployment
              if: ${{ github.event_name == 'push' && !contains(toJson(github.event.commits.*.message), '#skip') }}
              run: curl https://api.render.com/deploy/srv-${{ secrets.RENDER_SERVICE_ID }}?key=${{ secrets.RENDER_API_KEY }}

    tag_release: 
        needs: [simple_deployment_pipeline]
        runs-on: ubuntu-20.04
        steps: 
            - name: Checkout Repository
              uses: actions/checkout@v4

            - name: Bump version and push tag
              if: ${{ github.event_name == 'push' && !contains(toJson(github.event.commits.*.message), '#skip') }}
              uses: anothrNick/github-tag-action@1.64.0
              env:
                GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    inform_via_discord:
        needs: [tag_release]
        runs-on: ubuntu-20.04
        steps:
            - name: Test Success
              uses: rjstone/discord-webhook-notify@v1
              if: success()
              with:
                severity: info
                details: to https://github.com/nguyenductung2709-dt/Blog_Task by tung
                webhookUrl: ${{ secrets.DISCORD_WEBHOOK }}

            - name: Test Failure
              uses: rjstone/discord-webhook-notify@v1
              if: failure()
              with:
                severity: error
                details: "Commit by Tung broke the build. [Commit URL](${{ steps.commit_url.outputs.url }})"
                webhookUrl: ${{ secrets.DISCORD_WEBHOOK }}

            - name: Test Cancelled
              uses: rjstone/discord-webhook-notify@v1
              if: cancelled()
              with:
                severity: warn
                details: "There's some warning on the commit [Commit URL](${{ steps.commit_url.outputs.url }})"
                webhookUrl: ${{ secrets.DISCORD_WEBHOOK }}
